Pipeda Part A
opc-cpvp/online-complaint-form-pa_jf pull request #10
Opened 2020-10-02 18:47 UTC by jbrou015

2020-10-08 19:06 UTC, joshcampbell191 requested changes

2020-10-08 19:06 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/surveyHelper.ts
> +    }
Replace these with proper enum values.

2020-10-08 19:06 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/surveyHelper.ts
> +            return "";
Replace these with proper enum values.

2020-10-13 11:31 UTC, jbrou015 commented on ComplaintFormCore/ClientApp/src/pipeda/pipedaSurvey.ts
> +import { testData_pipeda } from "./pipeda_test_data";
This is my test data. I need this for now so I can test my stuff.

2020-10-13 11:46 UTC, jbrou015 commented on ComplaintFormCore/Web Apis/PipedaSurveyController.cs
> +            //throw new Exception("this is a test exception", new Exception("this is the inner exception"));
I guess I can always get it from the source control if need be.

2020-10-13 18:24 UTC, joshcampbell191 requested changes

2020-10-13 18:27 UTC, jbrou015 commented on ComplaintFormCore/ClientApp/src/pipeda/pipedaProvinceData.ts
> +    1: {
I can't get that thing using province name instead of id... do you know how?

2020-10-13 18:40 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/pipeda/pipedaProvinceData.ts
> +    1: {
You'll have to first change the const to the following type:

`export const PipedaProvincesData: Record<Province, PipedaProvince>`

Then you can declare your keys as follows:
`
[Province.Ontario]: { French: { ... } }, [Province.Quebec]: { French: { ... }}, ...
`

2020-10-13 18:42 UTC, jbrou015 commented on ComplaintFormCore/ClientApp/src/pipeda/pipedaProvinceData.ts
> +    1: {
Square brackets? ... interesting... thanks it works

2020-10-13 18:57 UTC, joshcampbell191 approved these changes

2020-10-13 18:58 UTC, merged