features/survey-refactor
opc-cpvp/online-complaint-form-pa_jf pull request #16
Opened 2020-11-12 19:44 UTC by joshcampbell191

2020-11-12 20:49 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/survey.ts
> +        });
Move to checkbox widget

2020-11-19 21:49 UTC, pierluc-ssoucy requested changes

2020-11-19 21:49 UTC, pierluc-ssoucy commented on ComplaintFormCore/ClientApp/src/widgets/filemeterwidget.ts
> +        JsonObject.metaData.removeProperty("file", "totalSize");
I understand the purpose, but is this really required?

2020-11-19 21:49 UTC, pierluc-ssoucy commented on ComplaintFormCore/ClientApp/src/widgets/checkboxwidget.ts
> +        JsonObject.metaData.removeProperty("checkbox", "renderAs");
There is a few instances of this one. Just by reading it, I find it slightly a bit confusing to not have the JsonObject class call prefixed with Survey.

2020-11-19 21:49 UTC, pierluc-ssoucy commented on ComplaintFormCore/ClientApp/src/index.ts
> +            FileMeterWidget.init();
This feels a bit odd, it's not the end of the world, but looks like its something that should be initialized automatically when used. If not we don't move forward with changing this, I feel like a name like "register" or something along those lines might better describe what's happening.

2020-11-23 22:52 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/index.ts
> +            FileMeterWidget.init();
These calls have been moved to `registerWidgets`.

2020-11-23 22:52 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/index.ts
> +            paSurvey.render();
A variable has been added to the `completedHtml` that gets set once the response is saved to the server.

2020-11-23 22:52 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/index.ts
> +            paSurvey.init(jsonUrl, lang, token);*/
Removed.

2020-11-23 22:52 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/pa/newPaSurvey.ts
> +    }
An abstract method `registerEventHandlers` has been added to the `SurveyBase` class.

2020-11-23 22:52 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/pa/newPaSurvey.ts
> +            const completeUrl = `/api/PASurvey/Complete?complaintId=${this.authToken}`;
Can be done at a later time.

2020-11-23 22:52 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/survey.ts
> +    });
The property has been changed to readonly.

2020-11-23 22:52 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/survey.ts
> +                link.innerText = `Error ${index++}: ${title.innerText} - ${error.getText()}`;
Localization has been added through `surveyLocalization`.

2020-11-23 22:52 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/survey.ts
> +        header.innerText = `The form could not be submitted because ${index - 1} error(s) were found.`;
Localization has been added through `surveyLocalization`.

2020-11-23 22:52 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/survey.ts
> +        });
The property has been moved to the checkbox widget.

2020-11-23 22:52 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/widgets/filemeterwidget.ts
> +        JsonObject.metaData.removeProperty("file", "totalSize");
These have been removed as I could only find them in a single widget. Worse case, we can always come back and re-add it.

2020-11-23 22:53 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/index.ts
> +            FileMeterWidget.init();
These have been moved to the `registerWidgets` method of `NewPaSurvey`.

2020-11-24 19:17 UTC, pierluc-ssoucy approved these changes

2020-11-24 19:18 UTC, merged