Pia tool up to 3 13
opc-cpvp/online-complaint-form-pa_jf pull request #17
Opened 2020-11-20 16:19 UTC by jbrou015

2020-11-23 14:22 UTC, joshcampbell191 requested changes

2020-11-23 14:22 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/pia/piaE-ToolSurvey.ts
> +                        if (pnd_PurposeOfDisclosure) {
Check if `pnd_PurposeOfDisclosure` is `null` and return to reduce arrow code.

2020-11-23 14:22 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/pia/piaE-ToolSurvey.ts
> +                            const receivingParties = pnd_PurposeOfDisclosure.templateElements[1] as Survey.QuestionDropdownModel;
Is it possible to get the column value by name instead of index?

2020-11-23 14:22 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/pia/piaE-ToolSurvey.ts
> +                            if (receivingParties) {
Check if `receivingParties` is `null` and return to reduce arrow code.

2020-11-23 14:22 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pia_e_tool.json
> +            "en": "<p>In assessing what is the appropriate retention period and whether it is time to dispose of personal information, an institution should consider the following points:</p><p><ul><
The opening `<p>` tag should be added to the beginning of the `description` instead of before the `<ul>`.

2020-11-23 14:22 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pia_e_tool.json
> +            "en": "<p><ul><li>How will information be shared with the third party (that is, by what means or channels?) </li><li>How will the receiving party protect the personal information (you can
The closing `</p>` tag should be placed after the last `</p>` tag instead of after the `</ul>`.

2020-11-23 14:22 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pia_e_tool.json
> +            "en": "<p><ul><li>How will information be shared with the third party (that is, by what means or channels?)</li><li>How will the receiving party protect the personal information (you can
The closing `</p>` tag should be placed after the last `</p>` tag instead of after the `</ul>`.

2020-11-23 14:22 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pia_e_tool.json
> +            "en": "<p>Examples include, but are not limited to</p><ul><li>Security clearances</li><li>Limiting access on a need-to-know basis</li><li>Other access restrictions</li><li>Regular reviews
An extra `<p>` tag should be added around the whole description in order to generate proper HTML once showdown strips it out.

2020-11-23 14:22 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pia_e_tool.json
> +            "en": "<p>Examples include, but are not limited to:</p><ul><li>Locked filing cabinets or safes</li><li>Combination locks</li><li>Secured premises</li><li>Access or key cards</li><li>Alarm
An extra `<p>` tag should be added around the whole description in order to generate proper HTML once showdown strips it out.

2020-11-23 14:22 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pia_e_tool.json
> +            "en": "<p>Examples include, but are not limited to:</p><p><ul><li>Identification requirements to establish legitimate identity for accessing personal information</li><li>Authentication (i
An extra `<p>` tag should be added around the whole description in order to generate proper HTML once showdown strips it out.

2020-11-23 14:22 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pia_e_tool.json
> +            "en": "<p>Please ensure your response answers the following questions:</p><p><ul><li>Is implied or express consent obtained?</li><li>Is consent sought for all personal information element
An extra `<p>` tag should be added around the whole description in order to generate proper HTML once showdown strips it out.

2020-11-23 14:22 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pia_e_tool.json
> +            "en": "<p>Please ensure your response answers the following questions:</p><p><ul><li>Is implied or express consent obtained?</li><li>Is consent sought for all personal information element
The opening `<p>` tag should be placed before the first one instead of before the `<ul>`.

2020-11-23 14:22 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pia_e_tool.json
> +            "en": "<p>Please ensure your response answers the following questions:</p><p><ul><li>Is implied or express consent obtained?</li><li>Is consent sought for all personal information element
The opening `<p>` tag should be placed before the first one instead of before the `<ul>`.

2020-11-23 17:50 UTC, jbrou015 commented on ComplaintFormCore/ClientApp/src/pia/piaE-ToolSurvey.ts
> +                            const receivingParties = pnd_PurposeOfDisclosure.templateElements[1] as Survey.QuestionDropdownModel;
Good catch!

2020-11-24 18:54 UTC, joshcampbell191 requested changes

2020-11-24 18:54 UTC, joshcampbell191 commented on NOTES.txt
> +    "fr": "Aucune pi�ce jointe n'a encore �t� t�l�charg�e."
Looks like the accented characters haven't been properly encoded.

2020-11-24 18:54 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pia_e_tool.json
> +            "en": "<p><ul><li>How will information be shared with the third party (that is, by what means or channels?) </li><li>How will the receiving party protect the personal information (you can
The description field requires an additional `<p>` tag around it otherwise it will get stripped by showdown.

2020-11-24 18:54 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/pia/piaE-ToolSurvey.ts
> +export function IsPhysicalFormat(params: any[]): boolean {
We should probably change this for a [calculated value](https://surveyjs.io/Documentation/Library#calculatedvalues).

2020-11-24 18:54 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/pia/piaE-ToolSurvey.ts
> +export function IsElectronicFormat(params: any[]): boolean {
We should probably change this for a [calculated value](https://surveyjs.io/Documentation/Library#calculatedvalues).

2020-11-24 18:54 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pia_e_tool.json
> +            "en": "<p>In assessing what is the appropriate retention period and whether it is time to dispose of personal information, an institution should consider the following points:<ul><li>Revi
The description field requires an additional `<p>` tag around it otherwise it will get stripped by showdown.

2020-11-24 18:54 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pia_e_tool.json
> +          "description": {
The description field requires an additional `<p>` tag around it otherwise it will get stripped by showdown.

2020-11-24 18:54 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pia_e_tool.json
> +            "en": "<p><ul><li>Please provide the name of the cloud provider. Note that there are specific approved cloud solutions for information at the Protected B level. If your institution is usi
The description field requires an additional `<p>` tag around it otherwise it will get stripped by showdown.

2020-11-24 18:54 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pia_e_tool.json
> +            "en": "<p>Examples include, but are not limited to<ul><li>Security clearances</li><li>Limiting access on a need-to-know basis</li><li>Other access restrictions</li><li>Regular reviews of
The description field requires an additional `<p>` tag around it otherwise it will get stripped by showdown.

2020-11-27 12:30 UTC, jbrou015 commented on NOTES.txt
> +    "fr": "Aucune pi�ce jointe n'a encore �t� t�l�charg�e."
Fixed by saving the file as UTF-8

2020-11-27 13:52 UTC, jbrou015 commented on ComplaintFormCore/ClientApp/src/pia/piaE-ToolSurvey.ts
> +export function IsPhysicalFormat(params: any[]): boolean {
Nice. I didn't know it existed.

2020-11-30 14:27 UTC, joshcampbell191 approved these changes

2020-12-02 19:08 UTC, merged