Pa survey refactor
opc-cpvp/online-complaint-form-pa_jf pull request #20
Opened 2020-12-04 15:15 UTC by jbrou015

2020-12-07 15:04 UTC, jbrou015 commented on ComplaintFormCore/ClientApp/src/pa/newPaSurvey.ts
> +        if (surveyObj.data["NatureOfComplaint"].filter(x => x === "NatureOfComplaintDenialOfAccess").length > 0) {
FYI I am trying to set this up with **calculatedValues**

2020-12-10 17:05 UTC, joshcampbell191 requested changes

2020-12-10 18:41 UTC, jbrou015 commented on ComplaintFormCore/ClientApp/src/pa/newPaSurvey.ts
> +                    size: responseData[file.name].size
It is the link associated to each file so when the file is clicked it knows where to fetch the file data. It is needed.

2020-12-10 18:42 UTC, jbrou015 commented on ComplaintFormCore/ClientApp/src/survey.ts
> +        this.storageName = storageName;
Looks like you've done it already!

2020-12-10 18:55 UTC, jbrou015 commented on ComplaintFormCore/ClientApp/src/widgets/filemeterwidget.ts
> +        }
Ok. The original code was creating a bug but it is now fixed.

2020-12-10 18:59 UTC, jbrou015 commented on ComplaintFormCore/wwwroot/sample-data/survey_pa_complaint.json
>      }
Ouch! This is a <ul> containing 5 <li> and 2 of them are always shown. If you want to do it this way we will need 6 different html elements not 2.

2020-12-10 23:46 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/survey.ts
> +    }
This was added to the survey.css

2020-12-10 23:46 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/models/localStorage.ts
> +﻿export interface LocalStorage {
This was already changed.

2020-12-10 23:48 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/survey.ts
> +        if (sender.isDisplayMode === true) {
No longer relevant.

2020-12-10 23:48 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/survey.ts
> +    }
No longer relevant.

2020-12-10 23:48 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/survey.ts
> +    }
No longer relevant.

2020-12-10 23:48 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pa_complaint.json
>      }
Let me check and see if there's anything else we can do for this.

2020-12-11 12:42 UTC, jbrou015 commented on ComplaintFormCore/ClientApp/src/pa/paSurvey.ts
> +import { SurveyLocalStorage } from "../surveyLocalStorage";
Yes but we're gonna get rid of paSurvey.ts soon

2020-12-11 15:00 UTC, joshcampbell191 approved these changes

2020-12-11 15:00 UTC, joshcampbell191 commented on ComplaintFormCore/ClientApp/src/pa/newPaSurvey.ts
> +                    size: responseData[file.name].size
Is the `size` property still required?

2020-12-11 15:13 UTC, merged