Pid survey
opc-cpvp/online-complaint-form-pa_jf pull request #25
Opened 2021-01-11 16:20 UTC by jbrou015

2021-01-13 13:33 UTC, joshcampbell191 requested changes

2021-01-13 13:33 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pid.json
> +          "type": "checkbox",
Should this question use radio buttons instead?

2021-01-13 13:33 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pid.json
> +          "type": "paneldynamic",
I think I like this! Could we change the colors of the add / remove buttons to make them standout more?

2021-01-13 13:33 UTC, joshcampbell191 commented on ComplaintFormCore/wwwroot/sample-data/survey_pid.json
> +          "type": "paneldynamic",
Please add `"panelCount": 1` so that it displays the dropdown by default (similar to question 4.0).

2021-01-21 14:11 UTC, jbrou015 commented on ComplaintFormCore/wwwroot/sample-data/survey_pid.json
> +          "type": "checkbox",
Good point but here are the requirements...

_Question 3.1
Has the institution considered other options for this disclosure, such as subsections 8(2)(a) through 8(2)(l) of the Privacy Act? 
Hover over pop up box: It is possible another legislative authority may be more appropriate for the disclosure. Please note that in certain circumstances, personal information cannot be disclosed under s 8(2)(m) of the Privacy Act, because its disclosure is prohibited by other legislation.
**(checkbox)** (mandatory field)
•	☐ Yes, the institution considered other options for this disclosure and determined that this is the most appropriate course of action
•	☐ No, the institution did not consider other options for this disclosure 
•	☐ No, subsections 8(2)(a) through 8(2)(l) of the Privacy Act do not apply for this disclosure_

2021-01-21 14:11 UTC, jbrou015 commented on ComplaintFormCore/wwwroot/sample-data/survey_pid.json
> +          "type": "checkbox",
We should confirm with the client @plbonneville

2021-01-27 13:43 UTC, jbrou015 commented on ComplaintFormCore/wwwroot/sample-data/survey_pid.json
> +          "type": "paneldynamic",
I have added the css class _btn btn-default_ and modified the text to add + and X for remove. Would it make sense to have the add button green and the remove button red?

2021-02-12 20:23 UTC, joshcampbell191 commented
The part for the data elements still feels confusing to me. Do you think it would be best to keep it as checkboxes and have separate pages / questions for each for the elements?

2021-03-01 21:56 UTC, joshcampbell191 approved these changes

2021-03-01 21:58 UTC, merged